def generate_cube_gcode(size=20, layer_height=0.2, nozzle_temp=200, bed_temp=60, filename="test_cube.gcode"):
    """
    Generates a simple G-code for a 3D printing test (20mm cube).
    """
    with open(filename, "w") as f:
        # Start G-code
        f.write(f"; Test Cube G-code (Generated by Antigravity)\n")
        f.write(f"; Size: {size}mm x {size}mm x {size}mm\n")
        f.write(f"M140 S{bed_temp} ; Set bed temp\n")
        f.write(f"M104 S{nozzle_temp} ; Set nozzle temp\n")
        f.write(f"M190 S{bed_temp} ; Wait for bed temp\n")
        f.write(f"M109 S{nozzle_temp} ; Wait for nozzle temp\n")
        f.write(f"G28 ; Home all axes\n")
        f.write(f"G90 ; Absolute positioning\n")
        f.write(f"M82 ; Absolute extrusion mode\n")
        f.write(f"G92 E0 ; Reset extrusion\n")
        f.write(f"G1 Z2.0 F3000 ; Lift nozzle\n")
        
        # Calculate number of layers
        layers = int(size / layer_height)
        e_per_mm = 0.05  # Approximate extrusion per mm
        
        # Print layers
        for layer in range(layers):
            z = (layer + 1) * layer_height
            f.write(f"\n; Layer {layer} (Z={z:.2f}mm)\n")
            f.write(f"G1 Z{z:.2f} F1500\n")
            
            # Simple square perimeter (20x20)
            # Starting point (0, 0)
            f.write(f"G1 X0 Y0 F3000 ; Move to start\n")
            
            # Draw square
            e = (layer * size * 4 * e_per_mm) # Accumulated extrusion
            
            # X+
            e += size * e_per_mm
            f.write(f"G1 X{size} Y0 E{e:.4f} F1200\n")
            
            # Y+
            e += size * e_per_mm
            f.write(f"G1 X{size} Y{size} E{e:.4f}\n")
            
            # X-
            e += size * e_per_mm
            f.write(f"G1 X0 Y{size} E{e:.4f}\n")
            
            # Y-
            e += size * e_per_mm
            f.write(f"G1 X0 Y0 E{e:.4f}\n")
            
        # End G-code
        f.write("\n; End of print\n")
        f.write("M104 S0 ; Turn off nozzle\n")
        f.write("M140 S0 ; Turn off bed\n")
        f.write("G28 X0 ; Home X axis\n")
        f.write("M84 ; Disable motors\n")
        
    print(f"G-code for {size}mm cube generated successfully: {filename}")

if __name__ == "__main__":
    generate_cube_gcode()
